# render.yaml
services:
  - type: web
    name: news-api-proxy
    env: node
    plan: free
    buildCommand: 'cd news-api-proxy && npm install'
    startCommand: 'cd news-api-proxy && node server.js'
    envVars:
      - key: API_KEY
        value: eb50e78b9f9e43f0b38b069618817a80 # Replace with your actual NewsAPI key
